### ISSUE TITLE
Where is the ros package "ur_robot_driver"

### ISSUE THREAD

**Issue by Daniel-CUHK** [yaesolKim/dual_ur_robotiq#23]
I can't find the package "ur_robot_driver" and the launch file robot_bringup.launch

**Comment by daeunSong** [comment]
Hi Daniel, 

Please follow our [wiki page](https://github.com/EwhaGlab/dual_ur_robotiq/wiki/Getting-Started) for getting started. 
You must git clone the Universal_ROS_Driver repo and also some others to make use of ours. 

Please feel free to open the issue again if you have further questions. 

Thanks!
